version: '3'
services:
  app:
    build:
        context: .
    command: deno run --allow-net ./src/app.ts
    volumes:
      - .:/src
    ports:
      - 8080:8080
    stdin_open: true
    tty: true  


